# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ParsioApp(object):
    def setupUi(self, ParsioApp):
        ParsioApp.setObjectName("ParsioApp")
        ParsioApp.resize(701, 367)
        
        # Set window icon
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Data\\icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ParsioApp.setWindowIcon(icon)
        
        ParsioApp.setStyleSheet("QWidget {\n"
"    background-color: #0B1D51;  /* dark blue */\n"
"    color: black;\n"
"    font-family: Arial, sans-serif;\n"
"    font-size: 14px;\n"
"}\n"
"QMenuBar {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #cccccc;\n"
"    font-family: Arial, sans-serif;\n"
"    font-size: 14px;\n"
"}\n"
"QMenuBar::item {\n"
"    background-color: white;\n"
"    color: black;\n"
"    padding: 4px 8px;\n"
"}\n"
"QMenuBar::item:selected {\n"
"    background-color: #f0f0f0;\n"
"    color: black;\n"
"}\n"
"QMenuBar::item:pressed {\n"
"    background-color: #e0e0e0;\n"
"    color: black;\n"
"}\n"
"QMenu {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #cccccc;\n"
"}\n"
"QMenu::item {\n"
"    background-color: white;\n"
"    color: black;\n"
"    padding: 4px 20px;\n"
"}\n"
"QMenu::item:selected {\n"
"    background-color: #f0f0f0;\n"
"    color: black;\n"
"}\n"
"QTextEdit {\n"
"    background-color: #D6D9E0;  /* light gray/blue */\n"
"    color: black;\n"
"    border: 1px solid #324A80;  /* medium dark blue border */\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton {\n"
"    background-color: #081B40;  /* darker blue */\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 15px;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1A2E6B;  /* lighter blue on hover */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #050E2A;  /* darkest blue on press */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(ParsioApp)
        self.centralwidget.setObjectName("centralwidget")
        self.main_layout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.main_layout.setObjectName("main_layout")
        self.log_board = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        self.log_board.setFont(font)
        self.log_board.setReadOnly(True)
        self.log_board.setObjectName("log_board")
        self.main_layout.addWidget(self.log_board)
        self.right_panel = QtWidgets.QVBoxLayout()
        self.right_panel.setObjectName("right_panel")
        self.btn_paste = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        self.btn_paste.setFont(font)
        self.btn_paste.setObjectName("btn_paste")
        self.right_panel.addWidget(self.btn_paste)
        self.btn_commit = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        self.btn_commit.setFont(font)
        self.btn_commit.setObjectName("btn_commit")
        self.right_panel.addWidget(self.btn_commit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.right_panel.addItem(spacerItem)
        self.main_layout.addLayout(self.right_panel)
        ParsioApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ParsioApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 701, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        ParsioApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ParsioApp)
        self.statusbar.setObjectName("statusbar")
        ParsioApp.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(ParsioApp)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(ParsioApp)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(ParsioApp)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(ParsioApp)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtWidgets.QAction(ParsioApp)
        self.actionExit.setObjectName("actionExit")
        self.actionCut = QtWidgets.QAction(ParsioApp)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(ParsioApp)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(ParsioApp)
        self.actionPaste.setObjectName("actionPaste")
        self.actionClear_Log = QtWidgets.QAction(ParsioApp)
        self.actionClear_Log.setObjectName("actionClear_Log")
        self.actionRefresh = QtWidgets.QAction(ParsioApp)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionFull_Screen = QtWidgets.QAction(ParsioApp)
        self.actionFull_Screen.setObjectName("actionFull_Screen")
        self.actionSettings = QtWidgets.QAction(ParsioApp)
        self.actionSettings.setObjectName("actionSettings")
        self.actionExport_Data = QtWidgets.QAction(ParsioApp)
        self.actionExport_Data.setObjectName("actionExport_Data")
        self.actionImport_Data = QtWidgets.QAction(ParsioApp)
        self.actionImport_Data.setObjectName("actionImport_Data")
        self.actionAbout = QtWidgets.QAction(ParsioApp)
        self.actionAbout.setObjectName("actionAbout")
        self.actionUser_Guide = QtWidgets.QAction(ParsioApp)
        self.actionUser_Guide.setObjectName("actionUser_Guide")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionClear_Log)
        self.menuView.addAction(self.actionRefresh)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionFull_Screen)
        self.menuTools.addAction(self.actionSettings)
        self.menuTools.addAction(self.actionExport_Data)
        self.menuTools.addAction(self.actionImport_Data)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionUser_Guide)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(ParsioApp)
        QtCore.QMetaObject.connectSlotsByName(ParsioApp)

    def retranslateUi(self, ParsioApp):
        _translate = QtCore.QCoreApplication.translate
        ParsioApp.setWindowTitle(_translate("ParsioApp", "Parsio - AI Job Application Tracker"))
        self.btn_paste.setText(_translate("ParsioApp", "Click Here To Paste"))
        self.btn_commit.setText(_translate("ParsioApp", "Commit Changes"))
        self.menuFile.setTitle(_translate("ParsioApp", "File"))
        self.menuEdit.setTitle(_translate("ParsioApp", "Edit"))
        self.menuView.setTitle(_translate("ParsioApp", "View"))
        self.menuTools.setTitle(_translate("ParsioApp", "Tools"))
        self.menuHelp.setTitle(_translate("ParsioApp", "Help"))
        self.actionNew.setText(_translate("ParsioApp", "New"))
        self.actionNew.setShortcut(_translate("ParsioApp", "Ctrl+N"))
        self.actionOpen.setText(_translate("ParsioApp", "Open"))
        self.actionOpen.setShortcut(_translate("ParsioApp", "Ctrl+O"))
        self.actionSave.setText(_translate("ParsioApp", "Save"))
        self.actionSave.setShortcut(_translate("ParsioApp", "Ctrl+S"))
        self.actionSave_As.setText(_translate("ParsioApp", "Save As..."))
        self.actionSave_As.setShortcut(_translate("ParsioApp", "Ctrl+Shift+S"))
        self.actionExit.setText(_translate("ParsioApp", "Exit"))
        self.actionExit.setShortcut(_translate("ParsioApp", "Ctrl+Q"))
        self.actionCut.setText(_translate("ParsioApp", "Cut"))
        self.actionCut.setShortcut(_translate("ParsioApp", "Ctrl+X"))
        self.actionCopy.setText(_translate("ParsioApp", "Copy"))
        self.actionCopy.setShortcut(_translate("ParsioApp", "Ctrl+C"))
        self.actionPaste.setText(_translate("ParsioApp", "Paste"))
        self.actionPaste.setShortcut(_translate("ParsioApp", "Ctrl+V"))
        self.actionClear_Log.setText(_translate("ParsioApp", "Clear Log"))
        self.actionClear_Log.setShortcut(_translate("ParsioApp", "Ctrl+L"))
        self.actionRefresh.setText(_translate("ParsioApp", "Refresh"))
        self.actionRefresh.setShortcut(_translate("ParsioApp", "F5"))
        self.actionFull_Screen.setText(_translate("ParsioApp", "Full Screen"))
        self.actionFull_Screen.setShortcut(_translate("ParsioApp", "F11"))
        self.actionSettings.setText(_translate("ParsioApp", "Settings"))
        self.actionSettings.setShortcut(_translate("ParsioApp", "Ctrl+,"))
        self.actionExport_Data.setText(_translate("ParsioApp", "Export Data"))
        self.actionImport_Data.setText(_translate("ParsioApp", "Import Data"))
        self.actionAbout.setText(_translate("ParsioApp", "About"))
        self.actionAbout.setShortcut(_translate("ParsioApp", "F1"))
        self.actionUser_Guide.setText(_translate("ParsioApp", "User Guide"))


if __name__ == "__main__":
    # Set app ID for Windows taskbar grouping (IMPORTANT for taskbar icon)
    if os.name == 'nt':  # Windows only
        try:
            import ctypes
            ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID('parsio.app.1.0')
        except:
            pass  # Ignore if this fails on non-Windows systems
    
    app = QtWidgets.QApplication(sys.argv)
    
    # Create icon and set it for the application
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap(".\\Data\\icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    
    # Set application icon (for taskbar)
    app.setWindowIcon(icon)
    
    # Create main window
    ParsioApp = QtWidgets.QMainWindow()
    ui = Ui_ParsioApp()
    ui.setupUi(ParsioApp)
    
    # Ensure window icon is set
    ParsioApp.setWindowIcon(icon)
    
    ParsioApp.show()
    sys.exit(app.exec_())